/**
 * Where the CV's sheets break, per language, as the block indices each sheet
 * holds.
 *
 * Generated by `scripts/paginate.js` from a real layout — run `pnpm paginate`
 * rather than editing it. Kept under version control because the build has no
 * browser to measure with, and shipped to the client as well as the server so
 * that the markup both produce is the same markup.
 */
export const PAGINATION: Record<string, number[][]> = {
	de: [
		[0, 1, 2],
		[3, 4, 5, 6, 7],
		[8, 9],
	],
	en: [
		[0, 1, 2],
		[3, 4, 5, 6, 7],
		[8, 9],
	],
};
