import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

/**
 * Emits the response headers Cloudflare Pages serves the site with (`_headers`
 * uses the same format Netlify introduced). Generated rather than written by
 * hand because the content policy has to name every inline script by hash: a
 * static host has no request to mint a nonce on, and a hash pasted into a
 * config file would go stale the moment the script it describes is edited —
 * silently, taking the theme restoration down with it.
 */
const DOCUMENT = "dist/index.html";
const HEADERS = "dist/_headers";

const html = readFileSync(DOCUMENT, "utf8");

/**
 * The theme/reader restoration script and the JSON-LD block. The linked-data
 * block is inert and browsers differ on whether the policy even applies to it,
 * so it is hashed too.
 */
const inline = [
	...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g),
].map((match) => match[1]);

if (inline.length !== 2) {
	throw new Error(
		`${DOCUMENT} has ${inline.length} inline scripts, expected the theme script and the JSON-LD block — has the head changed?`,
	);
}

const hashes = inline.map(
	(source) =>
		`'sha256-${createHash("sha256").update(source, "utf8").digest("base64")}'`,
);

const csp = [
	"default-src 'self'",
	// `unsafe-inline` alongside the hashes is not the contradiction it reads as:
	// any browser that understands a hash ignores it outright. It is there for
	// engines too old to understand one, which would otherwise refuse the theme
	// script and flash light-mode at every dark-mode visitor.
	`script-src 'self' 'unsafe-inline' ${hashes.join(" ")}`,
	"style-src 'self'",
	"img-src 'self' data:",
	"font-src 'self'",
	"connect-src 'self'",
	"object-src 'none'",
	"base-uri 'none'",
	"form-action 'none'",
	"frame-ancestors 'none'",
].join("; ");

/**
 * `immutable` is a promise that the bytes at these paths never change, which
 * the hashed filenames under `/assets` keep on their own. The fonts are named
 * by hand, so it is a promise this repository has to keep: replacing a `.woff2`
 * means giving it a new name, or a year of caches will go on serving the old one.
 */
const rules = `# Generated by scripts/headers.js — edit that, not this.

/*
  Content-Security-Policy: ${csp}
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Referrer-Policy: strict-origin-when-cross-origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(HEADERS, rules);

// info, not log: this is build progress on purpose, not a leftover debug print.
console.info(`wrote ${HEADERS} with ${hashes.length} script hashes`);
