import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { cvLocales, select, settled, withPage } from "./browser.js";

/**
 * Captures where the CV's sheets break, so the prerendered document can ship
 * already paginated instead of shipping one endless sheet and rearranging it
 * in front of the reader.
 *
 * A page break is a measurement — block heights against the capacity of a
 * sheet — and the server has no layout engine, so the measurement is taken
 * here, in a browser, and committed. Capacity is a 21cm × 29.7cm sheet with
 * fixed padding and self-hosted faces, so the answer is the same everywhere.
 * The browser still re-measures on load and still wins: being out of date
 * costs the flicker back, not a wrong document.
 */
const DIST = "dist";
const OUT = "src/components/cv/pagination.generated.ts";

/**
 * The sheets, as the number of blocks each one holds. Read off the rendered
 * document rather than out of the app's own state: the sheets are built by
 * mapping over the blocks in order, so counting their block children says
 * everything about where the breaks fell.
 */
const COUNTS = `(() => {
  const rig = document.querySelector('div[aria-hidden="true"][class*="200vw"]');
  return [...document.querySelectorAll('[class*="21cm"]')]
    .filter((sheet) => !rig || !rig.contains(sheet))
    .map((sheet) => {
      const flow = sheet.firstElementChild;
      return [...flow.children].filter((child) =>
        child.classList.contains("break-inside-avoid"),
      ).length;
    });
})()`;

/** Counts per sheet back into the index runs the paginator packs. */
function toPages(counts) {
	let next = 0;
	return counts.map((count) => Array.from({ length: count }, () => next++));
}

const locales = cvLocales();
if (!locales.length) {
	throw new Error("no cv.md documents under src/content/*/ to capture");
}

const pages = await withPage(DIST, async ({ evaluate, goto }) => {
	await goto("/cv");
	// The prerendered page is always the default locale.
	await evaluate(settled("en"));

	const captured = {};
	for (const locale of locales) {
		// Every language is measured in the same session by switching to it,
		// which is what the reader does too.
		await evaluate(select(locale));
		await evaluate(settled(locale));
		const counts = await evaluate(COUNTS);
		if (counts.some((count) => count === 0)) {
			throw new Error(
				`${locale} measured an empty sheet: ${counts.join(", ")}`,
			);
		}
		captured[locale] = toPages(counts);
	}
	return captured;
});

const body = Object.entries(pages)
	.map(([locale, sheets]) => `\t${locale}: ${JSON.stringify(sheets)},`)
	.join("\n");

writeFileSync(
	OUT,
	`/**
 * Where the CV's sheets break, per language, as the block indices each sheet
 * holds.
 *
 * Generated by \`scripts/paginate.js\` from a real layout — run \`pnpm paginate\`
 * rather than editing it. Kept under version control because the build has no
 * browser to measure with, and shipped to the client as well as the server so
 * that the markup both produce is the same markup.
 */
export const PAGINATION: Record<string, number[][]> = {
${body}
};
`,
);

// Whatever this emits has to survive `biome check` like anything else in src.
execFileSync("pnpm", ["exec", "biome", "format", "--write", OUT], {
	stdio: "ignore",
});

// info, not log: this is build progress on purpose, not a leftover debug print.
console.info(
	`captured pagination into ${OUT}: ${Object.entries(pages)
		.map(([locale, sheets]) => `${locale} ${sheets.length} sheets`)
		.join(", ")}`,
);
